### ISSUE TITLE
No X11 DISPLAY variable was set

### ISSUE THREAD

**Issue by dexon9109** [hartleys/igvSnap#1]
Hello, I am having a problem with X11 while running the test command.

I spent a lot of time trying, and I didn't have this problem with the other machine. There are always problems in the process of installing dependencies, I wonder if I have a relatively simple way to solve this problem?
I want to mass-produce screenshots of IGV on linux, but I don't normally use a display on linux, just run it interactively using the command line.

Hope to get your reply, thank you very much.

```
$java -Xmx4000m -jar /fuer2/02.pipeline/17.Somatic_panel/test/19.IGV_test/01.software/igvSnap-master/bin/igv.jar -b .//IGV_snapshots.bat
INFO [2024-03-13T14:37:15,706]  [DirectoryManager.java:179] [AWT-EventQueue-0]  IGV Directory: /fuer1/home/bioinfo/igv
INFO [2024-03-13T14:37:15,747]  [Main.java:155] [AWT-EventQueue-0]  Startup  IGV Version user not_set
INFO [2024-03-13T14:37:15,748]  [Main.java:156] [AWT-EventQueue-0]  Java 1.8.0_212
INFO [2024-03-13T14:37:15,748]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2024-03-13T14:37:15,777]  [Main.java:157] [AWT-EventQueue-0]  Default User Directory: /fuer1/home/bioinfo
INFO [2024-03-13T14:37:15,777]  [Main.java:158] [AWT-EventQueue-0]  OS: Linux
INFO [2024-03-13T14:37:15,805]  [Main.java:208] [Thread-4]  Unknown version: user
ERROR [2024-03-13T14:37:15,807]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[?:1.8.0_212]
	at java.awt.Window.<init>(Window.java:536) ~[?:1.8.0_212]
	at java.awt.Frame.<init>(Frame.java:420) ~[?:1.8.0_212]
	at java.awt.Frame.<init>(Frame.java:385) ~[?:1.8.0_212]
	at javax.swing.JFrame.<init>(JFrame.java:189) ~[?:1.8.0_212]
	at org.broad.igv.ui.Main$1.run(Main.java:106) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_212]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_212]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_212]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_212]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_212]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_212]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_212]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_212]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_212]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_212]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_212]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_212]
INFO [2024-03-13T14:37:16,866]  [ShutdownThread.java:46] [Thread-3]  Shutting down
```

**Comment by dexon9109** [comment]
There seems to be no problem after I use Xvfb.
